{{- if .Values.daprComponents.deploy }}
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: {{ .Values.daprComponents.pubsub.name }}
spec:
  type: pubsub.rabbitmq
  version: v1
  metadata:
  - name: host
    value: {{ .Values.daprComponents.pubsub.host }}
  - name: durable
    value: "false"
  - name: deletedWhenUnused
    value: "false"
  - name: autoAck
    value: "false"
  - name: reconnectWait
    value: "0"
  - name: concurrency
    value: parallel
{{ end }}