{{- if .Values.daprComponents.deploy }}
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: {{ .Values.daprComponents.state.name }}
spec:
  type: state.redis
  version: v1
  metadata:
  - name: redisHost
    value: {{ .Values.daprComponents.state.redisHost }}
  - name: redisPassword
    value: {{ .Values.daprComponents.state.redisPwd }}
  # - name: redisPassword
  #   secretKeyRef:
  #     name: redis
  #     key: redis-password
  - name: actorStateStore
    value: "true"
{{ end }}