apiVersion: skaffold/v2beta28
kind: Config
metadata:
  name: dapr on mars
build:
  artifacts:
  - image: rover
    context: apps/rover
    docker:
      dockerfile: Dockerfile
  - image: rover-1
    context: apps/rover
    docker:
      dockerfile: Dockerfile-1

deploy:
  helm:
    releases:
    - name: rover
      chartPath: ../deploy/helm/rover
      namespace: mars
      createNamespace: true
      artifactOverrides:
        image: rover # no tag present!
      imageStrategy:
        helm: {} 
    - name: rover-1
      chartPath: ../deploy/helm/rover-1
      namespace: mars
      createNamespace: true
      artifactOverrides:
        image: rover-1 # no tag present!
      imageStrategy:
        helm: {} 